server:
  port: 8080

spring:

  # jpa ??
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    defer-datasource-initialization: true

  # DB
  datasource:
    url: jdbc:mysql://localhost:3306/spring_test?useSSl=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jack
    password: jack

#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
##      settings:
##        trace: false
##        web-allow-others: false
#
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem://localhost/~/test;MODE=MYSQL
#    username: sa

  # Swagger ??
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

