server:
  port: 8080

spring:

  # jpa ??
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    defer-datasource-initialization: true

  # DB
  datasource:
    url: jdbc:mysql://localhost:3306/spring_test?useSSl=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jack
    password: jack

  # Swagger ??
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

